### ISSUE TITLE
How to use the human depth image on iphones?

### ISSUE THREAD

**Issue by adfansong** [natml-hub/MoveNet-3D-Sample#2]
Hello, I've tried to just replace the "TryAcquireEnvironmentDepthCpuImage" with "TryAcquireHumanDepthCpuImage", the results are not correct.

Could you please tell me how to use the human depth image?

**Comment by olokobayusuf** [comment]
Hey @adfansong , is there any reason why you are trying to use human depth instead of environment depth? Environment depth should be more accurate. Human depth might not be accurate enough to get the correct depth for each skeleton point.

**Comment by adfansong** [comment]
> Hey @adfansong , is there any reason why you are trying to use human depth instead of environment depth? Environment depth should be more accurate. Human depth might not be accurate enough to get the correct depth for each skeleton point.

Hello. I was trying to run the demo on my iphone, but TryAcquireEnvironmentDepthCpuImage failed, and according to your tips, TryAcquireHumanDepthCpuImage may work. So I had that question.

**Comment by olokobayusuf** [comment]
Ah I see. Yeah, I haven't investigated using human depth before. I recommend trying out BlazePose because it provides 3D landmarks also: https://github.com/natmlx/blazepose-unity
